### ISSUE TITLE
Not finding TBB correctly on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by dsilvavinicius** [justusc/FindTBB#7] opened 2016-11-16 18:35 UTC
After upgrading my Ubuntu 14 to 16.04 LTS, FindTBB started to output the following error. The  libtbb-dev package is installed (apt-get was used for that). Also, I'm using an updated version of FindTBB.cmake.

`  Could NOT find TBB (missing: TBB_LIBRARIES) (found version "4.4")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindTBB.cmake:256 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)
`

**Comment by justusc** [comment] 2016-11-17 04:22
Thank you for the bug report. I will look into the issue this weekend.

**Comment by justusc** [comment] 2016-11-19 16:33
I am sorry, but I was unable to reproduce the error you reported. I ran the `test.sh` script (with some modifications) on a clean install of Ubuntu 16.04.1. I also installed the git, cmake, and libtbb-dev packages.

Can you please pull the latest version of FindTBB and run `test.sh`. I would like to make sure that the test runs correctly. If the test passes, then the problem is either in your usage or you have found a corner case where FindTBB is failing.

**Comment by justusc** [comment] 2016-12-03 20:38
I am going to close this issue. If you have additional information (ideally steps to reproduce the problem or a minimal failing example), please feel free to reopen this issue or create a new issue.

**Closed as completed by justusc** 2016-12-03 20:38 UTC
